// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Warehouse.Infrastructure.Db;

#nullable disable

namespace Warehouse.Infrastructure.Migrations
{
    [DbContext(typeof(PostgresDbContext))]
    [Migration("20260715151634_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Warehouse.Domain.Models.BalanceEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint");

                    b.Property<long>("ResourceId")
                        .HasColumnType("bigint");

                    b.Property<long>("UnitId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UnitId");

                    b.HasIndex("ResourceId", "UnitId")
                        .IsUnique();

                    b.ToTable("Balances", t =>
                        {
                            t.HasCheckConstraint("ValidQuantity", "\"Quantity\" > 0");
                        });
                });

            modelBuilder.Entity("Warehouse.Domain.Models.ClientEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsArchive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Warehouse.Domain.Models.IncomeEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.ToTable("Incomes");
                });

            modelBuilder.Entity("Warehouse.Domain.Models.IncomeItemEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("IncomeId")
                        .HasColumnType("bigint");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint");

                    b.Property<long>("ResourceId")
                        .HasColumnType("bigint");

                    b.Property<long>("UnitId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("IncomeId");

                    b.HasIndex("ResourceId");

                    b.HasIndex("UnitId");

                    b.HasIndex("Id", "ResourceId", "UnitId")
                        .IsUnique();

                    b.ToTable("IncomeItems", t =>
                        {
                            t.HasCheckConstraint("ValidQuantity", "\"Quantity\" > 0");
                        });
                });

            modelBuilder.Entity("Warehouse.Domain.Models.ResourceEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("IsArchive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Resources");
                });

            modelBuilder.Entity("Warehouse.Domain.Models.ShipmentEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ClientId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<bool>("IsApprove")
                        .HasColumnType("boolean");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.ToTable("Shipments");
                });

            modelBuilder.Entity("Warehouse.Domain.Models.ShipmentItemEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint");

                    b.Property<long>("ResourceId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ShipmentId")
                        .HasColumnType("bigint");

                    b.Property<long>("UnitId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ResourceId");

                    b.HasIndex("ShipmentId");

                    b.HasIndex("UnitId");

                    b.HasIndex("Id", "ResourceId", "UnitId")
                        .IsUnique();

                    b.ToTable("ShipmentItems", t =>
                        {
                            t.HasCheckConstraint("ValidQuantity", "\"Quantity\" > 0");
                        });
                });

            modelBuilder.Entity("Warehouse.Domain.Models.UnitEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("IsArchive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Units");
                });

            modelBuilder.Entity("Warehouse.Domain.Models.BalanceEntity", b =>
                {
                    b.HasOne("Warehouse.Domain.Models.ResourceEntity", "Resource")
                        .WithMany("BalanceItems")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Warehouse.Domain.Models.UnitEntity", "Unit")
                        .WithMany("BalanceItems")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Warehouse.Domain.Models.IncomeItemEntity", b =>
                {
                    b.HasOne("Warehouse.Domain.Models.IncomeEntity", "Income")
                        .WithMany("IncomeItems")
                        .HasForeignKey("IncomeId");

                    b.HasOne("Warehouse.Domain.Models.ResourceEntity", "Resource")
                        .WithMany("IncomeItems")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Warehouse.Domain.Models.UnitEntity", "Unit")
                        .WithMany("IncomeItems")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Income");

                    b.Navigation("Resource");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Warehouse.Domain.Models.ShipmentEntity", b =>
                {
                    b.HasOne("Warehouse.Domain.Models.ClientEntity", "Client")
                        .WithMany("Shipments")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Warehouse.Domain.Models.ShipmentItemEntity", b =>
                {
                    b.HasOne("Warehouse.Domain.Models.ResourceEntity", "Resource")
                        .WithMany("ShipmentItems")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Warehouse.Domain.Models.ShipmentEntity", "Shipment")
                        .WithMany("ShipmentItems")
                        .HasForeignKey("ShipmentId");

                    b.HasOne("Warehouse.Domain.Models.UnitEntity", "Unit")
                        .WithMany("ShipmentItems")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");

                    b.Navigation("Shipment");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Warehouse.Domain.Models.ClientEntity", b =>
                {
                    b.Navigation("Shipments");
                });

            modelBuilder.Entity("Warehouse.Domain.Models.IncomeEntity", b =>
                {
                    b.Navigation("IncomeItems");
                });

            modelBuilder.Entity("Warehouse.Domain.Models.ResourceEntity", b =>
                {
                    b.Navigation("BalanceItems");

                    b.Navigation("IncomeItems");

                    b.Navigation("ShipmentItems");
                });

            modelBuilder.Entity("Warehouse.Domain.Models.ShipmentEntity", b =>
                {
                    b.Navigation("ShipmentItems");
                });

            modelBuilder.Entity("Warehouse.Domain.Models.UnitEntity", b =>
                {
                    b.Navigation("BalanceItems");

                    b.Navigation("IncomeItems");

                    b.Navigation("ShipmentItems");
                });
#pragma warning restore 612, 618
        }
    }
}
