CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260715151634_Initial') THEN
    CREATE TABLE "Clients" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "Address" character varying(500) NOT NULL,
        "IsArchive" boolean NOT NULL,
        "Name" character varying(200) NOT NULL,
        CONSTRAINT "PK_Clients" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260715151634_Initial') THEN
    CREATE TABLE "Incomes" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "Number" character varying(50) NOT NULL,
        "Date" date NOT NULL,
        CONSTRAINT "PK_Incomes" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260715151634_Initial') THEN
    CREATE TABLE "Resources" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "IsArchive" boolean NOT NULL,
        "Name" character varying(200) NOT NULL,
        CONSTRAINT "PK_Resources" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260715151634_Initial') THEN
    CREATE TABLE "Units" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "IsArchive" boolean NOT NULL,
        "Name" character varying(200) NOT NULL,
        CONSTRAINT "PK_Units" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260715151634_Initial') THEN
    CREATE TABLE "Shipments" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "Number" character varying(50) NOT NULL,
        "Date" date NOT NULL,
        "ClientId" bigint NOT NULL,
        "IsApprove" boolean NOT NULL,
        CONSTRAINT "PK_Shipments" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Shipments_Clients_ClientId" FOREIGN KEY ("ClientId") REFERENCES "Clients" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260715151634_Initial') THEN
    CREATE TABLE "Balances" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "ResourceId" bigint NOT NULL,
        "UnitId" bigint NOT NULL,
        "Quantity" bigint NOT NULL,
        CONSTRAINT "PK_Balances" PRIMARY KEY ("Id"),
        CONSTRAINT "ValidQuantity" CHECK ("Quantity" > 0),
        CONSTRAINT "FK_Balances_Resources_ResourceId" FOREIGN KEY ("ResourceId") REFERENCES "Resources" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Balances_Units_UnitId" FOREIGN KEY ("UnitId") REFERENCES "Units" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260715151634_Initial') THEN
    CREATE TABLE "IncomeItems" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "IncomeId" bigint,
        "ResourceId" bigint NOT NULL,
        "UnitId" bigint NOT NULL,
        "Quantity" bigint NOT NULL,
        CONSTRAINT "PK_IncomeItems" PRIMARY KEY ("Id"),
        CONSTRAINT "ValidQuantity" CHECK ("Quantity" > 0),
        CONSTRAINT "FK_IncomeItems_Incomes_IncomeId" FOREIGN KEY ("IncomeId") REFERENCES "Incomes" ("Id"),
        CONSTRAINT "FK_IncomeItems_Resources_ResourceId" FOREIGN KEY ("ResourceId") REFERENCES "Resources" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_IncomeItems_Units_UnitId" FOREIGN KEY ("UnitId") REFERENCES "Units" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260715151634_Initial') THEN
    CREATE TABLE "ShipmentItems" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "ShipmentId" bigint,
        "ResourceId" bigint NOT NULL,
        "UnitId" bigint NOT NULL,
        "Quantity" bigint NOT NULL,
        CONSTRAINT "PK_ShipmentItems" PRIMARY KEY ("Id"),
        CONSTRAINT "ValidQuantity" CHECK ("Quantity" > 0),
        CONSTRAINT "FK_ShipmentItems_Resources_ResourceId" FOREIGN KEY ("ResourceId") REFERENCES "Resources" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_ShipmentItems_Shipments_ShipmentId" FOREIGN KEY ("ShipmentId") REFERENCES "Shipments" ("Id"),
        CONSTRAINT "FK_ShipmentItems_Units_UnitId" FOREIGN KEY ("UnitId") REFERENCES "Units" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260715151634_Initial') THEN
    CREATE UNIQUE INDEX "IX_Balances_ResourceId_UnitId" ON "Balances" ("ResourceId", "UnitId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260715151634_Initial') THEN
    CREATE INDEX "IX_Balances_UnitId" ON "Balances" ("UnitId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260715151634_Initial') THEN
    CREATE UNIQUE INDEX "IX_Clients_Name" ON "Clients" ("Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260715151634_Initial') THEN
    CREATE UNIQUE INDEX "IX_IncomeItems_Id_ResourceId_UnitId" ON "IncomeItems" ("Id", "ResourceId", "UnitId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260715151634_Initial') THEN
    CREATE INDEX "IX_IncomeItems_IncomeId" ON "IncomeItems" ("IncomeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260715151634_Initial') THEN
    CREATE INDEX "IX_IncomeItems_ResourceId" ON "IncomeItems" ("ResourceId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260715151634_Initial') THEN
    CREATE INDEX "IX_IncomeItems_UnitId" ON "IncomeItems" ("UnitId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260715151634_Initial') THEN
    CREATE UNIQUE INDEX "IX_Incomes_Number" ON "Incomes" ("Number");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260715151634_Initial') THEN
    CREATE UNIQUE INDEX "IX_Resources_Name" ON "Resources" ("Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260715151634_Initial') THEN
    CREATE UNIQUE INDEX "IX_ShipmentItems_Id_ResourceId_UnitId" ON "ShipmentItems" ("Id", "ResourceId", "UnitId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260715151634_Initial') THEN
    CREATE INDEX "IX_ShipmentItems_ResourceId" ON "ShipmentItems" ("ResourceId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260715151634_Initial') THEN
    CREATE INDEX "IX_ShipmentItems_ShipmentId" ON "ShipmentItems" ("ShipmentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260715151634_Initial') THEN
    CREATE INDEX "IX_ShipmentItems_UnitId" ON "ShipmentItems" ("UnitId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260715151634_Initial') THEN
    CREATE INDEX "IX_Shipments_ClientId" ON "Shipments" ("ClientId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260715151634_Initial') THEN
    CREATE UNIQUE INDEX "IX_Shipments_Number" ON "Shipments" ("Number");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260715151634_Initial') THEN
    CREATE UNIQUE INDEX "IX_Units_Name" ON "Units" ("Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260715151634_Initial') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260715151634_Initial', '9.0.7');
    END IF;
END $EF$;
COMMIT;

